package lk.ijse.GrandView.util;

public enum Routes {
    LOG,ADMIN_DASHBOARD,EMPLOYEE,USER,HALL,ROOM,MEAL,ABOUT_US,CONTACT,FORGOT_PASSWORD,GET_OTP,CHANGE_PASSWORD,ADD_EMPLOYEE,USER_DASHBOARD,
    COMPLAINT,GUEST,MEAL_DETAIL,PAYMENT
}
